language: node_js
node_js:
    - "10"
SER_EMAIL}
AFTER_SCRIPT:
    - GITBOOK BUILD
    - CD ./_BOOK
    - GIT INIT
    - GIT CONFIG USER.NAME "${USER_NAME}"
    - GIT CONFIG USER.EMAIL "${USER_EMAIL}"
    - git add .
    - git commit -m "publish gitbook"
    - git push --force --quiet "https://${ACC_TOKEN}@${GH_REF}" master:${BRANCH}
                                  
branches:
    only:
      - main
